singleFR_col_pair = {'營業毛利率': 'Operating gross margin',
                     '營業利益率': 'Operating profit rate',
                     '稅前淨利率': 'Net interest rate before tax',
                     '稅後淨利率': 'Net interest rate after tax',
                     '稅後淨利率\xa0(母公司)': 'Net profit after tax  (parent company)',
                     '每股稅前盈餘\xa0(元)': 'Earnings per share before tax (yuan)',
                     '每股稅後盈餘\xa0(元)': 'Earnings per share after tax (yuan)',
                     '每股淨值\xa0(元)': 'Net value per share (yuan)',
                     '股東權益報酬率\xa0(當季)': "Return on shareholders' equity  (quarterly)",
                     '股東權益報酬率\xa0(年預估)': "Return on shareholders' equity  (annual estimate)",
                     '資產報酬率\xa0(當季)': 'Return on assets  (quarterly)',
                     '資產報酬率\xa0(年預估)': 'Return on assets  (annual estimate)',
                     '營收季成長率': 'Quarterly revenue growth rate',
                     '毛利季成長率': 'Gross profit growth rate',
                     '營業利益季成長率': 'Quarterly growth rate',
                     '稅前淨利季成長率': 'Quarterly net profit growth rate before tax',
                     '稅後淨利季成長率': 'Quarterly net profit growth rate after tax',
                     '稅後淨利季成長率\xa0(母公司)': 'Quarterly net profit growth rate after tax  (parent company)',
                     '每股稅後盈餘季成長率': 'Quarterly growth rate of earnings per share after tax',
                     '營收年成長率': 'Annual revenue growth rate',
                     '毛利年成長率': 'Gross profit growth rate',
                     '營業利益年成長率': 'Annual growth rate of operating profit',
                     '稅前淨利年成長率': 'Annual growth rate of net profit before tax',
                     '稅後淨利年成長率': 'Annual growth rate of net profit after tax',
                     '稅後淨利年成長率\xa0(母公司)': 'Annual growth rate of net profit after tax  (parent company)',
                     '每股稅後盈餘年成長率': 'Annual growth rate of earnings per share after tax',
                     '現金\xa0(%)': 'Cash (%)',
                     '應收帳款\xa0(%)': 'Accounts receivable (%)',
                     '存貨\xa0(%)': 'Inventory (%)',
                     '速動資產\xa0(%)': 'Quick assets (%)',
                     '流動資產\xa0(%)': 'Current assets (%)',
                     '基金與投資\xa0(%)': 'Funds and investments (%)',
                     '固定資產\xa0(%)': 'Fixed assets (%)',
                     '無形資產\xa0(%)': 'Intangible assets (%)',
                     '其他資產\xa0(%)': 'Other assets (%)',
                     '現金季成長率': 'Cash quarterly growth rate',
                     '應收帳款季成長率': 'Quarterly growth rate of accounts receivable',
                     '存貨季成長率': 'Inventory season growth rate',
                     '流動資產季成長率': 'Quarterly growth rate of current assets',
                     '基金與投資季成長率': 'Fund and investment quarterly growth rate',
                     '固定資產季成長率': 'Quarterly growth rate of fixed assets',
                     '無形資產季成長率': 'Quarterly growth rate of intangible assets',
                     '其他資產季成長率': 'Quarterly growth rate of other assets',
                     '資產總額季成長率': 'Quarterly growth rate of total assets',
                     '現金年成長率': 'Annual cash growth rate',
                     '應收帳款年成長率': 'Annual growth rate of accounts receivable',
                     '存貨年成長率': 'Annual inventory growth rate',
                     '流動資產年成長率': 'Annual growth rate of current assets',
                     '基金與投資年成長率': 'Annual growth rate of funds and investments',
                     '固定資產年成長率': 'Annual growth rate of fixed assets',
                     '無形資產年成長率': 'Annual growth rate of intangible assets',
                     '其他資產年成長率': 'Annual growth rate of other assets',
                     '資產總額年成長率': 'Annual growth rate of total assets',
                     '應付帳款\xa0(%)': 'Accounts payable (%)',
                     '流動負債\xa0(%)': 'Current liabilities (%)',
                     '長期負債\xa0(%)': 'Long-term liabilities (%)',
                     '其他負債\xa0(%)': 'Other liabilities (%)',
                     '負債總額\xa0(%)': 'Total liabilities (%)',
                     '普通股股本\xa0(%)': 'Common equity (%)',
                     '股東權益總額\xa0(%)': "Total shareholders' equity (%)",
                     '應付帳款季成長率': 'Quarterly growth rate of accounts payable',
                     '流動負債季成長率': 'Quarterly growth rate of current liabilities',
                     '長期負債季成長率': 'Long-term debt quarterly growth rate',
                     '其他負債季成長率': 'Other debt quarterly growth rate',
                     '負債總額季成長率': 'Quarterly growth rate of total debt',
                     '普通股股本季成長率': 'Common stock growth rate this quarter',
                     '股東權益總額季成長率': "Quarterly growth rate of total shareholders' equity",
                     '應付帳款年成長率': 'Annual growth rate of accounts payable',
                     '流動負債年成長率': 'Annual growth rate of current liabilities',
                     '長期負債年成長率': 'Long-term debt annual growth rate',
                     '其他負債年成長率': 'Annual growth rate of other liabilities',
                     '負債總額年成長率': 'Annual growth rate of total liabilities',
                     '普通股股本年成長率': 'Common stock annual growth rate',
                     '股東權益總額年成長率': "Annual growth rate of total shareholders' equity",
                     '現金比': 'Cash ratio',
                     '速動比': 'Quick Ratio',
                     '流動比': 'Current ratio',
                     '利息保障倍數': 'Interest coverage ratio',
                     '現金流量比\xa0(當季)': 'Cash flow ratio  (current quarter)',
                     '現金流量比\xa0(年預估)': 'Cash flow ratio  (annual estimate)',
                     '營業成本率': 'Operating cost rate',
                     '營業費用率': 'Operating expense ratio',
                     '應收帳款週轉率\xa0(次/年)': 'Accounts receivable turnover rate (times / year)',
                     '應收款項收現日數\xa0(日)': 'Days of cash receivable (days)',
                     '應付帳款週轉率\xa0(次/年)': 'Accounts payable turnover rate (times / year)',
                     '應付款項付現日數\xa0(日)': 'Number of days to pay cash (days)',
                     '存貨週轉率\xa0(次/年)': 'Inventory turnover rate (times / year)',
                     '平均售貨日數\xa0(日)': 'Average sales days (days)',
                     '固定資產週轉率\xa0(次/年)': 'Fixed asset turnover ratio (times / year)',
                     '總資產週轉率\xa0(次/年)': 'Turnover of total assets (times / year)',
                     '淨值週轉率\xa0(次/年)': 'Net worth turnover (times / year)',
                     '應收帳款佔營收比率\xa0(當季)': 'Accounts receivable as a percentage of revenue  (quarterly)',
                     '應收帳款佔營收比率\xa0(年預估)': 'Accounts receivable as a percentage of revenue  (annual estimate)',
                     '存貨佔營收比率\xa0(當季)': 'Inventory to revenue ratio  (quarterly)',
                     '存貨佔營收比率\xa0(年預估)': 'Inventory to revenue ratio  (annual estimate)',
                     '每股營業現金流量\xa0(元)': 'Operating cash flow per share (yuan)',
                     '每股投資現金流量\xa0(元)': 'Investment cash flow per share (yuan)',
                     '每股融資現金流量\xa0(元)': 'Financing cash flow per share (yuan)',
                     '每股淨現金流量\xa0(元)': 'Net cash flow per share (yuan)',
                     '每股自由現金流量\xa0(元)': 'Free cash flow per share (yuan)',
                     '負債對淨值比率': 'Debt to net worth ratio',
                     '長期資金適合率': 'Long-term funding suitability',
                     '所得稅佔稅前淨利比率': 'Income tax to net profit ratio before tax',
                     '業外損益佔營收比率': 'Non-operating profit and loss to revenue ratio',
                     '業外損益佔稅前淨利比率': 'Non-operating profit and loss as a percentage of net profit before tax',
                     '財報評分\xa0(100為滿分)': 'Earnings score (100 out of 100)'}
