# Generated by Django 2.2.7 on 2020-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('stock_name', models.CharField(max_length=100, null=True, verbose_name='證券名稱')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='開盤價')),
                ('close_price', models.FloatField(blank=True, null=True, verbose_name='收盤價')),
                ('high_price', models.FloatField(blank=True, null=True, verbose_name='最高價')),
                ('low_price', models.FloatField(blank=True, null=True, verbose_name='最低價')),
                ('turnover_vol', models.FloatField(blank=True, null=True, verbose_name='成交股數')),
                ('turnover_price', models.FloatField(blank=True, null=True, verbose_name='成交金額')),
            ],
        ),
    ]
