# Generated by Django 2.2.7 on 2020-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRevenueTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('stock_name', models.CharField(max_length=100, null=True, verbose_name='公司名稱')),
                ('this_month_rev', models.FloatField(blank=True, null=True, verbose_name='當月營收')),
                ('last_month_rev', models.FloatField(blank=True, null=True, verbose_name='上月營收')),
                ('last_year_rev', models.FloatField(blank=True, null=True, verbose_name='去年當月營收')),
                ('cp_last_month_rev', models.FloatField(blank=True, null=True, verbose_name='上月比較增減(%)')),
                ('cp_last_year_rev', models.FloatField(blank=True, null=True, verbose_name='去年同月增減(%)')),
                ('cm_this_month_rev', models.FloatField(blank=True, null=True, verbose_name='當月累計營收')),
                ('cm_last_month_rev', models.FloatField(blank=True, null=True, verbose_name='去年累計營收')),
                ('cp_cm_rev', models.FloatField(blank=True, null=True, verbose_name='前期比較增減(%)')),
                ('note', models.CharField(max_length=500, null=True, verbose_name='備註')),
            ],
        ),
    ]
