# Generated by Django 2.2.7 on 2020-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crawlers', '0002_monthlyrevenuetw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBasicInfoTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('update_time', models.DateTimeField(verbose_name='資料日期')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名稱')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司簡稱')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='產業類別')),
                ('registered_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='企業註冊地國')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司總部地址')),
                ('chairman', models.CharField(blank=True, max_length=100, null=True, verbose_name='董事長')),
                ('ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='總經理')),
                ('spokesman', models.CharField(blank=True, max_length=100, null=True, verbose_name='發言人')),
                ('spokesman_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='發言人職稱')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司總機')),
                ('establishment_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司成立日')),
                ('sii_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='上市日')),
                ('otc_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='上櫃日')),
                ('rotc_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='興櫃日')),
                ('capital', models.BigIntegerField(blank=True, null=True, verbose_name='資本額')),
                ('shares_issued', models.BigIntegerField(blank=True, null=True, verbose_name='普通股發行股本')),
                ('private_shares', models.BigIntegerField(blank=True, null=True, verbose_name='私募普通股數')),
                ('special_shares', models.BigIntegerField(blank=True, null=True, verbose_name='特別股數')),
                ('dividend_frequency',
                 models.CharField(blank=True, max_length=500, null=True, verbose_name='普通股盈餘分派或虧損撥補頻率')),
                ('stock_transfer_institution',
                 models.CharField(blank=True, max_length=500, null=True, verbose_name='股票過戶機構')),
                ('visa_accounting_firm',
                 models.CharField(blank=True, max_length=500, null=True, verbose_name='簽證會計師事務所')),
                ('website', models.CharField(blank=True, max_length=500, null=True, verbose_name='公司網址')),
                ('investor_relations_contact',
                 models.CharField(blank=True, max_length=500, null=True, verbose_name='投資人關係聯絡電話')),
                ('investor_relations_email',
                 models.CharField(blank=True, max_length=500, null=True, verbose_name='投資人關係聯絡電子郵件')),
                ('english_abbreviation', models.CharField(blank=True, max_length=500, null=True, verbose_name='英文簡稱')),
            ],
        ),
    ]
