# Generated by Django 2.2.8 on 2020-04-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0003_companybasicinfotw'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndexVolTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('turnover_vol', models.FloatField(blank=True, null=True, verbose_name='成交股數')),
                ('turnover_price', models.FloatField(blank=True, null=True, verbose_name='成交金額')),
                ('turnover_num', models.BigIntegerField(blank=True, null=True, verbose_name='成交筆數')),
            ],
        ),
        migrations.CreateModel(
            name='StockIndexPriceTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('index_price', models.FloatField(blank=True, null=True, verbose_name='指數點數')),
                ('quote_change', models.FloatField(blank=True, null=True, verbose_name='漲跌百分比')),
            ],
        ),
    ]
