# Generated by Django 2.2.8 on 2020-04-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0004_stockindexindextw_stockindexpricetw'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerInfoTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='券商代號')),
                ('broker_name', models.CharField(max_length=100, verbose_name='券商名稱')),
                ('date_of_establishment', models.CharField(max_length=100, verbose_name='券商建立日')),
                ('address', models.CharField(max_length=100, verbose_name='券商地址')),
                ('phone', models.CharField(max_length=100, verbose_name='市話')),
                ('department', models.CharField(max_length=100, verbose_name='券商部門')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
            ],
        ),
        migrations.AddField(
            model_name='companybasicinfotw',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='companybasicinfotw',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='經度'),
        ),
    ]
