# Generated by Django 2.2.8 on 2020-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0005_auto_20200425_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerinfotw',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='brokerinfotw',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='鄉鎮區'),
        ),
        migrations.AddField(
            model_name='companybasicinfotw',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='companybasicinfotw',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='鄉鎮區'),
        ),
    ]
