# Generated by Django 2.2.8 on 2020-05-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crawlers', '0007_brokertradetw'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTdccTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('stock_id_fk', models.CharField(max_length=100, verbose_name='證券價格外鍵')),
                ('hold_class', models.FloatField(blank=True, null=True, verbose_name='分級代號')),
                ('people', models.FloatField(blank=True, null=True, verbose_name='人數')),
                ('hold_num', models.FloatField(blank=True, null=True, verbose_name='持有股數')),
                ('hold_pt', models.FloatField(blank=True, null=True, verbose_name='分級占比')),
            ],
        ),
        migrations.CreateModel(
            name='StockTiiMarketReportTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('buy_price', models.FloatField(blank=True, null=True, verbose_name='買進金額')),
                ('sell_price', models.FloatField(blank=True, null=True, verbose_name='賣出金額')),
                ('net', models.FloatField(blank=True, null=True, verbose_name='買賣超金額')),
            ],
        ),
        migrations.CreateModel(
            name='StockTiiTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateTimeField(verbose_name='資料日期')),
                ('stock_name', models.CharField(max_length=100, null=True, verbose_name='證券名稱')),
                ('fm_buy', models.FloatField(blank=True, null=True, verbose_name='外陸資買進股數(不含外資自營商)')),
                ('fm_sell', models.FloatField(blank=True, null=True, verbose_name='外陸資賣出股數(不含外資自營商)')),
                ('fm_net', models.FloatField(blank=True, null=True, verbose_name='外陸資買賣超股數(不含外資自營商)')),
                ('fd_buy', models.FloatField(blank=True, null=True, verbose_name='外資自營商買進股數')),
                ('fd_sell', models.FloatField(blank=True, null=True, verbose_name='外資自營商賣出股數')),
                ('fd_net', models.FloatField(blank=True, null=True, verbose_name='外資自營商買賣超股數')),
                ('ft_net', models.FloatField(blank=True, null=True, verbose_name='全外資買賣超股數')),
                ('itc_buy', models.FloatField(blank=True, null=True, verbose_name='投信買進股數')),
                ('itc_sell', models.FloatField(blank=True, null=True, verbose_name='投信賣出股數')),
                ('itc_net', models.FloatField(blank=True, null=True, verbose_name='投信買賣超股數')),
                ('dealer_ppt_buy', models.FloatField(blank=True, null=True, verbose_name='自營商買進股數(自行買賣)')),
                ('dealer_ppt_sell', models.FloatField(blank=True, null=True, verbose_name='自營商賣出股數(自行買賣)')),
                ('dealer_ppt_net', models.FloatField(blank=True, null=True, verbose_name='自營商買賣超股數(自行買賣)')),
                ('dealer_hedge_buy', models.FloatField(blank=True, null=True, verbose_name='自營商買進股數(避險')),
                ('dealer_hedge_sell', models.FloatField(blank=True, null=True, verbose_name='自營商賣出股數(避險')),
                ('dealer_hedge_net', models.FloatField(blank=True, null=True, verbose_name='自營商買賣超股數(避險')),
                ('dealer_net', models.FloatField(blank=True, null=True, verbose_name='全自營商買賣超股數')),
                ('tii_net', models.FloatField(blank=True, null=True, verbose_name='三大法人買賣超股數')),
            ],
        ),
        migrations.AddField(
            model_name='brokertradetw',
            name='net_bs_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='買賣超金額'),
        ),
        migrations.AddField(
            model_name='stockpricetw',
            name='market',
            field=models.CharField(default=None, max_length=100, verbose_name='市場別'),
        ),
        migrations.AddField(
            model_name='companybasicinfotw',
            name='market',
            field=models.CharField(default=None, max_length=100, verbose_name='市場別'),
        ),
    ]
