# Generated by Django 2.2.8 on 2020-05-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0008_auto_20200502_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokertradetw',
            name='company_info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.CompanyBasicInfoTW', verbose_name='公司資訊'),
        ),
        migrations.AddField(
            model_name='stocktdcctw',
            name='company_info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.CompanyBasicInfoTW', verbose_name='公司資訊'),
        ),
        migrations.AddField(
            model_name='stocktdcctw',
            name='price_info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.StockPriceTW', verbose_name='股價資訊'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='update_time',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stockindexpricetw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stockindexvoltw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stocktdcctw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stocktiimarketreporttw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='date',
            field=models.DateField(verbose_name='資料日期'),
        ),
    ]
