# Generated by Django 2.2.8 on 2020-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0009_auto_20200503_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktdcctw',
            name='company_info',
        ),
        migrations.RemoveField(
            model_name='stocktdcctw',
            name='price_info',
        ),
        migrations.RemoveField(
            model_name='stocktdcctw',
            name='stock_id_fk',
        ),
        migrations.AddField(
            model_name='brokertradetw',
            name='broker_name',
            field=models.CharField(default=None, max_length=100, verbose_name='券商名稱'),
        ),
        migrations.AddField(
            model_name='StockTiiMarketReportTW',
            name='market',
            field=models.CharField(default=None, max_length=10, verbose_name="市場別"),
        ),
    ]
