# Generated by Django 3.0.5 on 2020-07-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0011_auto_20200508_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInsiderHoldDetailTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateField(verbose_name='資料日期')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='職稱')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='姓名')),
                ('act_hold', models.FloatField(blank=True, null=True, verbose_name='選任時持股')),
                ('hold', models.FloatField(blank=True, null=True, verbose_name='目前持股')),
                ('pledge', models.FloatField(blank=True, null=True, verbose_name='質押股數')),
                ('pledge_ratio', models.FloatField(blank=True, null=True, verbose_name='質押比例')),
                ('family_hold', models.FloatField(blank=True, null=True, verbose_name='配偶或未成年子女持股')),
                ('family_pledge', models.FloatField(blank=True, null=True, verbose_name='配偶或未成年子女質押股數')),
                ('family_pledge_ratio', models.FloatField(blank=True, null=True, verbose_name='配偶或未成年子女質押比例')),
            ],
            options={
                'db_table': 'stock_insider_hold_detail_tw',
            },
        ),
        migrations.CreateModel(
            name='StockInsiderHoldTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateField(verbose_name='資料日期')),
                ('stock_name', models.CharField(max_length=100, null=True, verbose_name='證券名稱')),
                ('issued_num', models.FloatField(blank=True, null=True, verbose_name='發行股數')),
                ('director_add', models.FloatField(blank=True, null=True, verbose_name='董監增持')),
                ('director_lower', models.FloatField(blank=True, null=True, verbose_name='董監減持')),
                ('director_hold', models.FloatField(blank=True, null=True, verbose_name='董監持股')),
                ('director_hold_ratio', models.FloatField(blank=True, null=True, verbose_name='董監持股比率')),
                ('manager_hold', models.FloatField(blank=True, null=True, verbose_name='經理人持股')),
                ('big10_hold', models.FloatField(blank=True, null=True, verbose_name='持有10趴以上持有人持股')),
            ],
            options={
                'db_table': 'stock_insider_hold_tw',
            },
        ),
        migrations.AlterUniqueTogether(
            name='brokertradetw',
            unique_together={('stock_id', 'date', 'broker_name')},
        ),
        migrations.AlterUniqueTogether(
            name='futurepricetw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrevenuetw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stock3pratiotw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stockindexpricetw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stockindexvoltw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stockpricetw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktdcctw',
            unique_together={('stock_id', 'date', 'hold_class')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktiimarketreporttw',
            unique_together={('stock_id', 'date', 'market')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktiitw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='brokerinfotw',
            index=models.Index(fields=['stock_id'], name='broker_info_stock_i_f09633_idx'),
        ),
        migrations.AddIndex(
            model_name='commoditytaifex',
            index=models.Index(fields=['stock_id'], name='commodity_t_stock_i_35f7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='companybasicinfotw',
            index=models.Index(fields=['stock_id'], name='company_inf_stock_i_20512a_idx'),
        ),
        migrations.AlterModelTable(
            name='brokerinfotw',
            table='broker_info_tw',
        ),
        migrations.AlterModelTable(
            name='brokertradetw',
            table='broker_trade_tw',
        ),
        migrations.AlterModelTable(
            name='commoditytaifex',
            table='commodity_taifex_tw',
        ),
        migrations.AlterModelTable(
            name='companybasicinfotw',
            table='company_info_tw',
        ),
        migrations.AlterModelTable(
            name='futurepricetw',
            table='future_price_tw',
        ),
        migrations.AlterModelTable(
            name='monthlyrevenuetw',
            table='monthly_revenue_tw',
        ),
        migrations.AlterModelTable(
            name='stock3pratiotw',
            table='stock_3P_ratio_tw',
        ),
        migrations.AlterModelTable(
            name='stockindexpricetw',
            table='stock_index_price_tw',
        ),
        migrations.AlterModelTable(
            name='stockindexvoltw',
            table='stock_index_vol_tw',
        ),
        migrations.AlterModelTable(
            name='stockpricetw',
            table='stock_price_tw',
        ),
        migrations.AlterModelTable(
            name='stocktdcctw',
            table='stock_tdcc_tw',
        ),
        migrations.AlterModelTable(
            name='stocktiimarketreporttw',
            table='stock_tii_market_tw',
        ),
        migrations.AlterModelTable(
            name='stocktiitw',
            table='stock_tii_tw',
        ),
        migrations.AlterUniqueTogether(
            name='stockmargintransactionstw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterModelTable(
            name='stockmargintransactionstw',
            table='stock_margin_transactions_tw',
        ),
        migrations.AlterUniqueTogether(
            name='stockinsiderholdtw',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stockinsiderholddetailtw',
            unique_together={('stock_id', 'date')},
        ),
    ]

