# Generated by Django 3.0.5 on 2020-07-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0012_auto_20200704_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerinfotw',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='brokerinfotw',
            name='district',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='鄉鎮區'),
        ),
        migrations.AlterField(
            model_name='brokerinfotw',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='brokerinfotw',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='broker_info',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.BrokerInfoTW', verbose_name='券商資訊'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='buy_num',
            field=models.FloatField(null=True, verbose_name='買進'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='company_info',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.CompanyBasicInfoTW', verbose_name='公司資訊'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='net_bs',
            field=models.FloatField(null=True, verbose_name='買賣超'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='net_bs_cost',
            field=models.FloatField(null=True, verbose_name='買賣超金額'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='sell_num',
            field=models.FloatField(null=True, verbose_name='賣出'),
        ),
        migrations.AlterField(
            model_name='brokertradetw',
            name='transactions_pt',
            field=models.FloatField(null=True, verbose_name='成交占比'),
        ),
        migrations.AlterField(
            model_name='commoditytaifex',
            name='company_info',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.CompanyBasicInfoTW', verbose_name='公司資訊'),
        ),
        migrations.AlterField(
            model_name='commoditytaifex',
            name='spot_unit',
            field=models.FloatField(null=True, verbose_name='契約現貨單位'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='公司總部地址'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='capital',
            field=models.BigIntegerField(null=True, verbose_name='資本額'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='產業類別'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='ceo',
            field=models.CharField(max_length=100, null=True, verbose_name='總經理'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='chairman',
            field=models.CharField(max_length=100, null=True, verbose_name='董事長'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='district',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='鄉鎮區'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='dividend_frequency',
            field=models.CharField(max_length=100, null=True, verbose_name='普通股盈餘分派或虧損撥補頻率'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='english_abbreviation',
            field=models.CharField(max_length=100, null=True, verbose_name='英文簡稱'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='establishment_date',
            field=models.CharField(max_length=100, null=True, verbose_name='公司成立日'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='investor_relations_contact',
            field=models.CharField(max_length=500, null=True, verbose_name='投資人關係聯絡電話'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='investor_relations_email',
            field=models.CharField(max_length=500, null=True, verbose_name='投資人關係聯絡電子郵件'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='latitude',
            field=models.FloatField(default=None, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='longitude',
            field=models.FloatField(default=None, null=True, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='otc_date',
            field=models.CharField(max_length=100, null=True, verbose_name='上櫃日'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='公司總機'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='private_shares',
            field=models.BigIntegerField(null=True, verbose_name='私募普通股數'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='registered_country',
            field=models.CharField(max_length=500, null=True, verbose_name='企業註冊地國'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='rotc_date',
            field=models.CharField(max_length=100, null=True, verbose_name='興櫃日'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='shares_issued',
            field=models.BigIntegerField(null=True, verbose_name='普通股發行股本'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='short_name',
            field=models.CharField(max_length=100, null=True, verbose_name='公司簡稱'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='sii_date',
            field=models.CharField(max_length=100, null=True, verbose_name='上市日'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='special_shares',
            field=models.BigIntegerField(null=True, verbose_name='特別股數'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='spokesman',
            field=models.CharField(max_length=100, null=True, verbose_name='發言人'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='spokesman_title',
            field=models.CharField(max_length=100, null=True, verbose_name='發言人職稱'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='stock_transfer_institution',
            field=models.CharField(max_length=100, null=True, verbose_name='股票過戶機構'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='visa_accounting_firm',
            field=models.CharField(max_length=100, null=True, verbose_name='簽證會計師事務所'),
        ),
        migrations.AlterField(
            model_name='companybasicinfotw',
            name='website',
            field=models.CharField(max_length=500, null=True, verbose_name='公司網址'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='best_ask',
            field=models.FloatField(null=True, verbose_name='最後最佳賣價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='best_bid',
            field=models.FloatField(null=True, verbose_name='最後最佳買價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='close',
            field=models.FloatField(null=True, verbose_name='收盤價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='commodity_info',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawlers.CommodityTaifex', verbose_name='公司資訊'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='cross_contract_vol',
            field=models.FloatField(null=True, verbose_name='價差對單式委託成交量'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='high',
            field=models.FloatField(null=True, verbose_name='最高價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='low',
            field=models.FloatField(null=True, verbose_name='最低價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='open',
            field=models.FloatField(null=True, verbose_name='開盤價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='open_interest',
            field=models.FloatField(null=True, verbose_name='未沖銷契約數'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='quote_change',
            field=models.FloatField(null=True, verbose_name='漲跌幅'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='settlement_price',
            field=models.FloatField(null=True, verbose_name='結算價'),
        ),
        migrations.AlterField(
            model_name='futurepricetw',
            name='turnover_vol',
            field=models.FloatField(null=True, verbose_name='成交量'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='cm_last_month_rev',
            field=models.FloatField(null=True, verbose_name='去年累計營收'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='cm_this_month_rev',
            field=models.FloatField(null=True, verbose_name='當月累計營收'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='cp_cm_rev',
            field=models.FloatField(null=True, verbose_name='前期比較增減(%)'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='cp_last_month_rev',
            field=models.FloatField(null=True, verbose_name='上月比較增減(%)'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='cp_last_year_rev',
            field=models.FloatField(null=True, verbose_name='去年同月增減(%)'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='last_month_rev',
            field=models.FloatField(null=True, verbose_name='上月營收'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='last_year_rev',
            field=models.FloatField(null=True, verbose_name='去年當月營收'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuetw',
            name='this_month_rev',
            field=models.FloatField(null=True, verbose_name='當月營收'),
        ),
        migrations.AlterField(
            model_name='stock3pratiotw',
            name='dividend_yield',
            field=models.FloatField(null=True, verbose_name='殖利率'),
        ),
        migrations.AlterField(
            model_name='stock3pratiotw',
            name='pb',
            field=models.FloatField(null=True, verbose_name='本淨比'),
        ),
        migrations.AlterField(
            model_name='stock3pratiotw',
            name='pe',
            field=models.FloatField(null=True, verbose_name='本益比'),
        ),
        migrations.AlterField(
            model_name='stockindexpricetw',
            name='index_price',
            field=models.FloatField(null=True, verbose_name='指數點數'),
        ),
        migrations.AlterField(
            model_name='stockindexpricetw',
            name='quote_change',
            field=models.FloatField(null=True, verbose_name='漲跌百分比'),
        ),
        migrations.AlterField(
            model_name='stockindexvoltw',
            name='turnover_num',
            field=models.BigIntegerField(null=True, verbose_name='成交筆數'),
        ),
        migrations.AlterField(
            model_name='stockindexvoltw',
            name='turnover_price',
            field=models.FloatField(null=True, verbose_name='成交金額'),
        ),
        migrations.AlterField(
            model_name='stockindexvoltw',
            name='turnover_vol',
            field=models.FloatField(null=True, verbose_name='成交股數'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='act_hold',
            field=models.FloatField(null=True, verbose_name='選任時持股'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='family_hold',
            field=models.FloatField(null=True, verbose_name='配偶或未成年子女持股'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='family_pledge',
            field=models.FloatField(null=True, verbose_name='配偶或未成年子女質押股數'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='family_pledge_ratio',
            field=models.FloatField(null=True, verbose_name='配偶或未成年子女質押比例'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='hold',
            field=models.FloatField(null=True, verbose_name='目前持股'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='pledge',
            field=models.FloatField(null=True, verbose_name='質押股數'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholddetailtw',
            name='pledge_ratio',
            field=models.FloatField(null=True, verbose_name='質押比例'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='big10_hold',
            field=models.FloatField(null=True, verbose_name='持有10趴以上持有人持股'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='director_add',
            field=models.FloatField(null=True, verbose_name='董監增持'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='director_hold',
            field=models.FloatField(null=True, verbose_name='董監持股'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='director_hold_ratio',
            field=models.FloatField(null=True, verbose_name='董監持股比率'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='director_lower',
            field=models.FloatField(null=True, verbose_name='董監減持'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='issued_num',
            field=models.FloatField(null=True, verbose_name='發行股數'),
        ),
        migrations.AlterField(
            model_name='stockinsiderholdtw',
            name='manager_hold',
            field=models.FloatField(null=True, verbose_name='經理人持股'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='cash_redemption',
            field=models.FloatField(null=True, verbose_name='融資現償'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='mt_balance_now',
            field=models.FloatField(null=True, verbose_name='今日融資餘額'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='mt_balance_pd',
            field=models.FloatField(null=True, verbose_name='前日融資餘額'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='mt_buy',
            field=models.FloatField(null=True, verbose_name='融資買進'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='mt_quota',
            field=models.FloatField(null=True, verbose_name='融資限額'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='mt_sell',
            field=models.FloatField(null=True, verbose_name='融資賣出'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='mt_use_rate',
            field=models.FloatField(null=True, verbose_name='融資使用率'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='note',
            field=models.CharField(max_length=500, null=True, verbose_name='官方註記'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='offset',
            field=models.FloatField(null=True, verbose_name='資券相抵'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='short_covering',
            field=models.FloatField(null=True, verbose_name='融券回補'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='short_sale',
            field=models.FloatField(null=True, verbose_name='融券賣出'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='ss_balance_now',
            field=models.FloatField(null=True, verbose_name='今日融券餘額'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='ss_balance_pd',
            field=models.FloatField(null=True, verbose_name='前日融券餘額'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='ss_quota',
            field=models.FloatField(null=True, verbose_name='券限額'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='ss_use_rate',
            field=models.FloatField(null=True, verbose_name='融券使用率'),
        ),
        migrations.AlterField(
            model_name='stockmargintransactionstw',
            name='stock_redemption',
            field=models.FloatField(null=True, verbose_name='融券現償'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='close_price',
            field=models.FloatField(null=True, verbose_name='收盤價'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='high_price',
            field=models.FloatField(null=True, verbose_name='最高價'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='low_price',
            field=models.FloatField(null=True, verbose_name='最低價'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='open_price',
            field=models.FloatField(null=True, verbose_name='開盤價'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='turnover_price',
            field=models.FloatField(null=True, verbose_name='成交金額'),
        ),
        migrations.AlterField(
            model_name='stockpricetw',
            name='turnover_vol',
            field=models.FloatField(null=True, verbose_name='成交股數'),
        ),
        migrations.AlterField(
            model_name='stocktdcctw',
            name='hold_class',
            field=models.FloatField(null=True, verbose_name='分級代號'),
        ),
        migrations.AlterField(
            model_name='stocktdcctw',
            name='hold_num',
            field=models.FloatField(null=True, verbose_name='持有股數'),
        ),
        migrations.AlterField(
            model_name='stocktdcctw',
            name='hold_pt',
            field=models.FloatField(null=True, verbose_name='分級占比'),
        ),
        migrations.AlterField(
            model_name='stocktdcctw',
            name='people',
            field=models.FloatField(null=True, verbose_name='人數'),
        ),
        migrations.AlterField(
            model_name='stocktiimarketreporttw',
            name='buy_price',
            field=models.FloatField(null=True, verbose_name='買進金額'),
        ),
        migrations.AlterField(
            model_name='stocktiimarketreporttw',
            name='net',
            field=models.FloatField(null=True, verbose_name='買賣超金額'),
        ),
        migrations.AlterField(
            model_name='stocktiimarketreporttw',
            name='sell_price',
            field=models.FloatField(null=True, verbose_name='賣出金額'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_hedge_buy',
            field=models.FloatField(null=True, verbose_name='自營商買進股數(避險'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_hedge_net',
            field=models.FloatField(null=True, verbose_name='自營商買賣超股數(避險'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_hedge_sell',
            field=models.FloatField(null=True, verbose_name='自營商賣出股數(避險'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_net',
            field=models.FloatField(null=True, verbose_name='全自營商買賣超股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_ppt_buy',
            field=models.FloatField(null=True, verbose_name='自營商買進股數(自行買賣)'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_ppt_net',
            field=models.FloatField(null=True, verbose_name='自營商買賣超股數(自行買賣)'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='dealer_ppt_sell',
            field=models.FloatField(null=True, verbose_name='自營商賣出股數(自行買賣)'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='fd_buy',
            field=models.FloatField(null=True, verbose_name='外資自營商買進股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='fd_net',
            field=models.FloatField(null=True, verbose_name='外資自營商買賣超股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='fd_sell',
            field=models.FloatField(null=True, verbose_name='外資自營商賣出股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='fm_buy',
            field=models.FloatField(null=True, verbose_name='外陸資買進股數(不含外資自營商)'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='fm_net',
            field=models.FloatField(null=True, verbose_name='外陸資買賣超股數(不含外資自營商)'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='fm_sell',
            field=models.FloatField(null=True, verbose_name='外陸資賣出股數(不含外資自營商)'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='ft_net',
            field=models.FloatField(null=True, verbose_name='全外資買賣超股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='itc_buy',
            field=models.FloatField(null=True, verbose_name='投信買進股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='itc_net',
            field=models.FloatField(null=True, verbose_name='投信買賣超股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='itc_sell',
            field=models.FloatField(null=True, verbose_name='投信賣出股數'),
        ),
        migrations.AlterField(
            model_name='stocktiitw',
            name='tii_net',
            field=models.FloatField(null=True, verbose_name='三大法人買賣超股數'),
        ),
        migrations.CreateModel(
            name='StockDivideRatioTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, verbose_name='證券代號')),
                ('date', models.DateField(verbose_name='資料日期')),
                ('stock_name', models.CharField(max_length=100, null=True, verbose_name='證券名稱')),
                ('divide_before', models.FloatField(null=True, verbose_name='除權息前股價')),
                ('divide_after', models.FloatField(null=True, verbose_name='除權息後股價')),
                ('divide_open', models.FloatField(null=True, verbose_name='除權息後開盤基準價')),
                ('divide_value', models.FloatField(null=True, verbose_name='權息值')),
                ('divide_category', models.CharField(max_length=50, null=True, verbose_name='除權息種類')),
                ('divide_ratio', models.FloatField(null=True, verbose_name='還原比率')),
            ],
            options={
                'db_table': 'stock_divide_ratio_tw',
                'unique_together': {('stock_id', 'date', 'divide_category')},
            },
        ),
    ]
